Homework 2 recyclerview
AlisherRMA/OtusLessons pull request #2
Opened 2021-02-06 08:15 UTC by AlisherRMA

2021-02-07 15:59 UTC, baidala requested changes
вообщем сделано хорошо. надо исправить переходы Home/Favorite/Home/Favorite.  и когда на одном фильме кликать на сердечко несколько раз(fav/notFav)  - этот фильм добавляется в Избранное несколько раз.

2021-02-07 15:59 UTC, baidala commented on .idea/dictionaries/Alisher.xml
> +<component name="ProjectDictionaryState">
.idea/  можно добавить в  gitignore

2021-02-07 15:59 UTC, baidala commented on app/src/main/res/layout/activity_favorites.xml
> +        app:layout_constraintBottom_toBottomOf="parent"
низ должен быть привязан к верху bottomNavView чтоб масштабировалось нормально на разных екранах

2021-02-07 15:59 UTC, baidala commented on app/src/main/java/ru/otus/otushometask1/favorites/FavoritesActivity.kt
> +                        startActivity(this)
если 6 раз переключится на Favorite потом на Home  - в стеке у вас несколько FavoriteActivity   MainActivity.  в MainActivity  вы используете startActivity, а в FavoriteActivity  вы просто закрываете текущее активити (а не заново стартуете  MainActivity )

2021-02-07 15:59 UTC, baidala commented on app/src/main/res/layout-land/item_films.xml
> +            app:icon_size="14dp"
best practice - min icon size  24dp 
можно 32dp
48dp

2021-02-07 15:59 UTC, baidala commented on app/src/main/res/layout/item_films.xml
> +            app:icon_size="10sp"
best practice - min icon size  24dp   - DP
можно 32dp
48dp

2021-02-08 16:05 UTC, AlisherRMA commented on app/src/main/res/layout-land/item_films.xml
> +            app:icon_size="14dp"
Указал 24dp

2021-02-08 16:06 UTC, AlisherRMA commented on app/src/main/java/ru/otus/otushometask1/favorites/FavoritesActivity.kt
> +                        startActivity(this)
Переписал на startActivityForResult

2021-02-08 16:06 UTC, AlisherRMA commented on app/src/main/res/layout/activity_favorites.xml
> +        app:layout_constraintBottom_toBottomOf="parent"
Поправил

2021-02-08 16:06 UTC, AlisherRMA commented on .idea/dictionaries/Alisher.xml
> +<component name="ProjectDictionaryState">
Добавил в gitignore

2021-02-11 12:52 UTC, merged